import type { Metadata } from "next";
// Theme
import { Plus_Jakarta_Sans } from "next/font/google";
import "@/styles/globals.css";
// Components
import Navigation from '@/components/navigation'

const fontFamily = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontFamily.className} bg-white`}>
        <div className="mx-auto max-w-screen-2xl px-16 pt-24">
          <div className="flex space-x-4">
            <div className="flex-none w-1/4">
              <Navigation />
            </div>
            <div className="flex-auto">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
